// reactjs/eosio-react-toodo/src/components/TodoList.js
import React from 'react';
import TodoListItem from './TodoListItem';

class TodoList extends React.Component {
  render() {
    const list = this.props.list.map((item) => {
      return <TodoListItem
        key={item.id}
        name={item.label}
        onClick={() => this.props.toggleItem(item.id)}
        checked={item.done}
      />
    })
    return (
      <div style={{width:'70%'}}>
        {list}
      </div>
    );
  }
}

export default TodoList;

// vue/vue-eosio-todo/client/src/components/TodoList.vue
<template>
  <div>
      <ul>
          <TodoListItem v-for="item in todoItems"
            :name="item.name" :key="item.name"/>
      </ul>
  </div>
</template>

<script>
import TodoListItem from './TodoListItem';
import connect from '../eosio';

export default {
    name: "TodoList",
    props: {
        accountName: String
    },
    data() {
        return {
            todoItems: [
                {
                    name: "Apples",
                    done: true
                },
                {
                    name: "Pears",
                    done: false
                },
            ]
        }
    },
    components: {
        TodoListItem
    },
    created() {
        connect();
    }
}
</script>

<style scoped>

</style>
